### ISSUE TITLE
Unable to clear credentials 

### ISSUE THREAD

**Issue by mrsheraton** [microsoft/vscode-powerquery-sdk#243]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.2

### Regression From

0.2.2

### Platform

Windows

### Architecture

x64

### OS Version

Windows Server 2016 DataCenter (Azure)

### VSCode version

1.75.1

### PQSdkTool Path

c:\Users\mark\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.2-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\PQTest.exe

### Bug Description

When creating a new (vanilla) project and attempting to run or just clear the credentials get an error.
(Was working prevously)

### Steps to Reproduce

As above, very simple.

### Actual Experience

As above, very simple.

### Expected Experience

As above, very simple.

### Additional Context

[9:38:02 AM]	[Info]	[Task found] c:\Users\mark\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.2-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\PQTest.exe delete-credential
				--prettyPrint
				--ALL
[9:38:02 AM]	[Error]	[Task exited abnormally] pqtest delete-credential pid(5164) exit(3762504530) stderr: Exception occurred while setting up credential store.

Unhandled Exception: System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at PQTest.Common.FileCredentialStore.Load()
   at PQTest.Console.Program.GetConfigurationWithCredentialStore(CommandLineApplication app, CommandLineApplication command)
   at PQTest.Console.Program.RunCredentialCommand(CommandLineApplication app, CommandLineApplication command, Action`1 invoke, DataSourceSetting dataSourceSetting)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at PQTest.Console.Program.Main(String[] args)

**Comment by mrsheraton** [comment]
I created a new VM this time running windows server 2022 and no such error, so putting it down to some compatibility issue with 2016.
